# Build With RestDocs
name: CI On Push

on:
  push:
    branches: [ "feat/jongwan/github-page" ]

  # Allows you to run this workflow manually from the Actions tab
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write
# Allow only one concurrent deployment, skipping runs queued between the run in-progress and latest queued.
# However, do NOT cancel in-progress runs as we want to allow these production deployments to complete.
concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3

      - name: Set up JDK 17
        uses: actions/setup-java@v3
        with:
          java-version: '17'
          distribution: 'temurin'

      - name: Grant execute permission for gradlew
        run: chmod +x ./gradlew
        shell: bash

      - name: Build with Gradle
        run: ./gradlew build
        shell: bash

      - name: Upload output file
        uses: actions/upload-artifact@v3
        with:
          name: docs
          path: build/docs/asciidoc/index.html
  # Single deploy job since we're just deploying
  deploy:
    needs: build
    environment:
      name: github-pages
      url: https://f-lab-edu.github.io/outfit-of-the-day
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Download a docs file
        uses: actions/download-artifact@v3
        with:
          name: docs

      - name: Setup Pages
        uses: actions/configure-pages@v3

      - name: console2
        run: ls -al

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v2
        with:
          path: '.'

      - name: console2
        run: cat ./index.html

      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v2





